### ISSUE TITLE
Add support for window/progress

### ISSUE THREAD

**Issue by mpickering** [alanz/haskell-lsp#144]
https://github.com/Microsoft/vscode-languageserver-node/pull/261

Vscode and sourcegraph clients implement this at least.

**Comment by bubba** [comment]
Should `haskell-lsp` provide a function in `LspFuncs` to communicate progress? Or is it enough just to expose the types and let the server take care of sending the notifications?

**Comment by alanz** [comment]
I think the more we can push into haskell-lsp the better.  It has a force-multiplier effect.
