### ISSUE TITLE
Commercial user GPL cleanup

### ISSUE THREAD

**Issue by alanz** [alanz/haskell-lsp#16]
https://github.com/alanz/haskell-lsp/pull/15 introduced a GPL library for the Virtual File System Feature.

This is a performance optimisation, and is localised to that module.

Any future commercial user will have to file a PR to either

- replace the library with an alternative (it is basically a `Data.Text` interface)
- let the initial setup include a structure containing the methods from `Yi.Rope` that are used, and pass in a non-GPL variant for commercial use, thus preserving performance for non-commercial users
- From GHC 8.2, use backpack to define a mixin with the features required, and use some non-GPL alternative

This issue simply captures the state of play, I (@alanz) have no intention of fixing it.

**Comment by cocreature** [comment]
Given that the PR to switch to rope-utf16-splay has been merged, I believe that this issue can be closed.
