### ISSUE TITLE
Relative file paths

### ISSUE THREAD

**Issue by DavidM-D** [alanz/haskell-lsp#167]
When converting to and from a relative file path (shown here https://github.com/digital-asset/haskell-lsp/commit/ee1e650a1aa3a06e7b33466c754cbd6b35bde963) you lose the first folder to the uriRegName field casing `file/path` to become `/path`. Should I add support for relative file paths or can I add a function that explicitly rejects unsupported filepath types?
Thanks
David

**Comment by alanz** [comment]
We have been taking the approach in haskell-ide-engine of converting all paths to absolute ones, because of inconsistent behaviour otherwise.

This is especially true if the cwd is not something that is clearly defined, or can change depending on how precisely the language server is started.

**Comment by DavidM-D** [comment]
We take the approach of having the cwd always be the project root as we found we were pulling peoples filepaths into our build artifacts. We can work around this quirk by just changing our paths from `file/path` to `./file/path` but it makes more sense for the fix to be upstreamed. What would you prefer the result of `uriToFilePath $ filePathToUri "relative/path"` to be? `Nothing`, `Just "file/path"` or keep it as it is?
