### ISSUE TITLE
Update to current state of progress proposal

### ISSUE THREAD

**Issue by cocreature** [alanz/haskell-lsp#184]
The proposal for reporting progress has changed quite significantly since it was added to `haskell-lsp`. There is now a branch for LSP 3.15 that contains the current state https://github.com/microsoft/language-server-protocol/blob/dbaeumer/3.15/specification.md so hopefully the current state is somewhat final and we can update haskell-lsp to use it.

**Comment by alanz** [comment]
Would anyone like to prepare a PR?

**Comment by cocreature** [comment]
I’ll try to find the time but I’m not sure when I’ll get around to it.

**Comment by cocreature** [comment]
I have a first draft of this at https://github.com/cocreature/haskell-lsp/tree/new-progress and a branch of ghcide that makes use of it and seems to work at https://github.com/digital-asset/ghcide/tree/fix-progress. It needs more work to get it into a mergable state so if anyone wants to help out, let me know or make a PR against my branch.
