### ISSUE TITLE
Change response type to contain `Either a ResponseError`

### ISSUE THREAD

**Issue by bubba** [alanz/haskell-lsp#191]
> This seems to be another hint at the fact that we should change this to something like `Either a ResponseError` but that would be a breaking change so I would at least do that in a separate PR whereas this is only breaking if you rely on the behavior on invalid `json-rpc` messages.

_Originally posted by @cocreature in https://github.com/alanz/haskell-lsp/pull/189#issuecomment-541631689_

**Comment by alanz** [comment]
Revisiting this, I think it is something we should do.

```typescript
interface ResponseMessage extends Message {
	/**
	 * The request id.
	 */
	id: number | string | null;

	/**
	 * The result of a request. This member is REQUIRED on success.
	 * This member MUST NOT exist if there was an error invoking the method.
	 */
	result?: string | number | boolean | object | null;

	/**
	 * The error object in case a request fails.
	 */
	error?: ResponseError;
}
```

is pretty explicit that `result` and `error` are (a) mutually exclusive and (b) one of them should be present.

Well, the requirement for something on error is not *as* explicit, but is pretty strong. And we already have this behaviour encoded in out test generators.

**Comment by greenhat** [comment]
I'd like to tackle this issue. I suppose the solution is to change `ResponseMessage`
from:
```haskell
data ResponseMessage a =
  ResponseMessage
    { _jsonrpc :: Text
    , _id      :: LspIdRsp
    , _result  :: Maybe a
    , _error   :: Maybe ResponseError
    } deriving (Read,Show,Eq)
```
 to:
```haskell
data ResponseMessage a =
  ResponseMessage
    { _jsonrpc :: Text
    , _id      :: LspIdRsp
    , _result  :: Either ResponseError a
    } deriving (Read,Show,Eq)
```
combining `_result` and `_error` into single `_result :: Either ResponseError a`. Is this the desired solution?

However, I'm not sure I get 
>so I would at least do that in a separate PR whereas this is only breaking if you rely on the behavior on invalid json-rpc messages.

Could @cocreature please clarify?

I can also try to do PRs to dependent projects: ghcide, haskell-language-server (what else?) to accommodate this breaking change.

**Comment by alanz** [comment]
I think this is worth doing, as it clarifies the usage of the message.  The important thing is to ensure that well formed JSON is generated and consumed.

Erroneous JSON (either both or neither fields present) should generate a JSON error, and get dealt with as usual.

> I can also try to do PRs to dependent projects: ghcide, haskell-language-server (what else?) to accommodate this breaking change.

I don't thing that is an absolute requirement.  This will go out with a major version bump anyway, and downstream projects tend to be tightly locked to a major version already.
