### ISSUE TITLE
Prepare 0.17 release

### ISSUE THREAD

**Issue by alanz** [alanz/haskell-lsp#193]
We need a new release, because code actions are currently missing in haskell-ide-engine.

The two major changes over 0.16 are the new progress mechanism, and the code action capability logic.

Is there anything else that needs to go in before release? Apart from a matching lsp-test.

**Comment by alanz** [comment]
cc @cocreature @bubba @fendor @mpickering

**Comment by cocreature** [comment]
From my side, everything should be ready for a release. With https://github.com/bubba/lsp-test/pull/54 merged, `lsp-test` also seems to work for us together with current `haskell-lsp` master.

**Comment by bubba** [comment]
Will start this now

**Comment by alanz** [comment]
Great. I was just thinking of doing it myself, then fell down this changelog rabbit hole: https://coderwall.com/p/5cv5lg/generate-your-changelogs-with-git-log

But at least you can do lsp-test at the same time.

**Comment by bubba** [comment]
I just ran `git log 0.16.0.0..HEAD` myself! It's pretty handy. The `--merge` option is especially great for aggregating the big feature changes and eliminating the noise

**Comment by bubba** [comment]
Done in 2aacc5c
