### ISSUE TITLE
Publish on hackage?

### ISSUE THREAD

**Issue by wiz** [alanz/haskell-lsp#2]
I've accidentally wrote an LSP library of my own as I was unaware of this one until just now. Unfortunately I can't publish it due to legal roadblocks so it is up to you to shine the glorious compatibility on us all :smile:

**Comment by alanz** [comment]
Ok, it is pretty much a work in progress, but I agree that in the interest of preventing duplication it is worth doing.

**Comment by alanz** [comment]
PS, Pull requests welcome

**Comment by alanz** [comment]
And in the meantime I updated https://github.com/Microsoft/language-server-protocol/issues/8#issuecomment-267149937

**Comment by wz1000** [comment]
I think we can close this now?
