### ISSUE TITLE
Discussion: should the repo be transferred into the haskell github org?

### ISSUE THREAD

**Issue by alanz** [alanz/haskell-lsp#202]

**Comment by Anrock** [comment]
What benefits does it bring? More "official" status of project?

**Comment by cocreature** [comment]
From my side, this doesn’t really matter. `haskell-lsp` very much feels like a community project already (thanks for being a great maintainer @alanz!) and I don’t think moving it around helps in any way.

**Comment by lorenzo** [comment]
One of the problems of the haskell org is that admins are usually not around, and activating things like new CI systems takes a long time.

**Comment by jneira** [comment]
It seems the consensus was not move it so i think we can close it (we can reopen if someone brings new arguments)
