### ISSUE TITLE
Refactor file uris to make possible skip normalization

### ISSUE THREAD

**Issue by jneira** [alanz/haskell-lsp#212]
* After #205 normalization could happen up to 2 times: in `filePathToUri` and `toNormalizeUri`, the last one to ensure that file `NormalizedUri`'s from other sources (like Aeson) are always normalized (and fix a bug in hie)
* Moreover, if client code already has ensured that filepaths are normalized it suffer the penalty of two additional normalizations:
  * It happened in ghcid: https://github.com/digital-asset/ghcide/pull/303 with a notable perfomance degradation (it is called many times)
  * So it was neccesary to inline the code of `filePathToUri`to avoid the extra normalization
* To avoid this, `filePathToUri` should remove the normalization, moving it to `normalizeUri` and maybe to another function `filePathToNormalizedUri :: FilePath -> NormalizedUri`

**Comment by cocreature** [comment]
One option would be to move `NormalizedFilePath` to `haskell-lsp`. Then we can provide a safe `NormalizedFilePath -> NormalizedUri` function that can skip normalization.

**Comment by alanz** [comment]
@cocreature sounds good to me. Would anyone like to make a PR?

**Comment by jneira** [comment]
@alanz i am afraid i dont know the ghcide codebase enough to implement @cocreature suggestion, does worth make a first small step like the described one in my comment?

For the more advanced refactoring i would enforce (maybe optionally) that file paths are absolute (`NormalizedAbsoluteFilePath`?), cause file uri's must be absolute by the standard and afaik hie and ghcide already use them.

**Comment by jneira** [comment]
I am working on this.
