### ISSUE TITLE
Add haskell-lsp and haskell-lsp-types to Stackage?!

### ISSUE THREAD

**Issue by sjakobi** [alanz/haskell-lsp#227]
That would allow `dhall-lsp-server` to be added. :)

**Comment by alanz** [comment]
Are they not in stackage? I am sure they were, not sure what happened.

**Comment by alanz** [comment]
Just checked, they are there. What snapshot and version is the problem?

**Comment by sjakobi** [comment]
Oops, I think I just misread the error when running `stack init --resolver nightly` on the latest `dhall-lsp-server` release which isn't compatible with `haskell-lsp-0.20` yet.

Sorry for the noise!
