### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by alanz** [alanz/haskell-lsp#237]
We have had a number of changes land recently, I think we should make a new release.

My thinking is to do it with the current state, and let #234 land in a later one, so people can experiment with it from master initially.

This allows the benefits of current improvements/bug fixes without having to change downstream code too much.

Thoughts?

cc @cocreature @bubba

**Comment by cocreature** [comment]
Making a release without #234 sounds great :+1:

**Comment by bubba** [comment]
Sounds good to me
