### ISSUE TITLE
Support for GHC 8.10

### ISSUE THREAD

**Issue by sjakobi** [alanz/haskell-lsp#239]
I'm just opening this issue to be notified once there's a release compatible with GHC 8.10. :)

**Comment by bubba** [comment]
The bounds were adjusted in #241 so the next release should support 8.10

**Comment by bubba** [comment]
@sjakobi haskell-lsp-0.22 should be on Hackage now

**Comment by sjakobi** [comment]
Thanks a lot @bubba! :)
