### ISSUE TITLE
/tmp/ doesn't exist on windows

### ISSUE THREAD

**Issue by archaeron** [alanz/haskell-lsp#3]
tries to write to a tmp file. But this doesn't work on windows
https://github.com/alanz/haskell-lsp/blob/a36eb6276d81df33fad835f50982c51ec312691f/src/Language/Haskell/LSP/Control.hs#L38

**Comment by alanz** [comment]
Fixed via https://github.com/alanz/haskell-lsp/commit/200fef72860036534fbfee8ab3f12328835432b3
