### ISSUE TITLE
Inconsistency in naming of NotificationParams

### ISSUE THREAD

**Issue by noughtmare** [alanz/haskell-lsp#49]
The notification params for the `Initialized` notification are called `InitializedParams`, but the params for the `Exit` notification are called `ExitNotificationParams`. I think they should either both contain the word `Notification` or neither.

I personally think `ExitNotificationParams` should be changed to `ExitParams`. `TraceNotificationParams` should then also be renamed to `TraceParams`.

**Comment by alanz** [comment]
@noughtmare I have added you as a collaborator.

You are welcome to file PRs too, rather than just issues.

And in general we hang out on #haskell-ide-engine on freenode.
