### ISSUE TITLE
FromJSON instance drops fields

### ISSUE THREAD

**Issue by noughtmare** [alanz/haskell-lsp#51]
```json
{
    "jsonrpc":"2.0",
    "id":0,
    "method":"client/registerCapability",
    "params":{
        "registrations":[{
            "registerOptions":{
                "documentSelector":{
                    "language":"haskell"
                }
            },
            "method":"workspace/executeCommand",
            "id":"hare:demote"
        },{
            "registerOptions":{
                "documentSelector":{
                    "language":"haskell"
                }
            },
            "method":"textDocument/definition",
            "id":"hare:gotodef"
        }]
    }
}
```
Gets parsed with `decode message :: Maybe (LSP.ResponseMessage Value)` as
```haskell
Just (ResponseMessage "2.0" (IdRspInt 0) Nothing Nothing)
```
While it should return `Nothing` (because it is not a response message).

I use it here:
https://github.com/noughtmare/haskell-lsp-client/blob/a954f85e9451c6bdfb05bc2fcad0ee81f1b059df/src/Main.hs#L146

**Comment by wz1000** [comment]
That is the default way aesons automatically derived instances work.

**Comment by wz1000** [comment]
One thing we could do to solve this is change the type of `_result` to `a` from `Maybe a`, and explicitly specify the `Maybe` when we need it.

**Comment by noughtmare** [comment]
I fixed it by using the fact that either the `_result` or the `_error` has to be a `Just ...` and the other has to be a `Nothing`.

See: https://github.com/noughtmare/haskell-lsp-client/blob/56b9d714b9c55047c2ed7059cfe270230cfb4b1c/src/Main.hs#L138

**Comment by noughtmare** [comment]
@wz1000 I don't really see how your solution would work. Do you think it would work better than my solution?

Maybe we should just request an `Option` to be added to make the automatically derived `FromJSON` parser stricter. Or we could write our own custom parser.

**Comment by alanz** [comment]
@noughtmare See the equivalent processing on the server side here https://github.com/alanz/haskell-lsp/blob/master/src/Language/Haskell/LSP/Core.hs#L358

Basically the first step is to check the kind of the message, and then use the functions from https://github.com/alanz/haskell-lsp/blob/master/src/Language/Haskell/LSP/Messages.hs to manage the actual messages.

**Comment by noughtmare** [comment]
For future reference, I think the server side processing is now:
https://github.com/alanz/haskell-lsp/blob/b747454c06686620762dcb6e35564dd15361c7d4/src/Language/Haskell/LSP/Core.hs#L422

**Comment by noughtmare** [comment]
My current solution is:
https://github.com/noughtmare/haskell-lsp-client/blob/d2806a9a598f30271337324a10fab667a482fb6c/src/LSP/Client.hs#L209-L226

I'm not completely satisfied, because it relies on failing JSON decoding, but I think it is the best I can do so I am closing this issue.
