### ISSUE TITLE
Not a valid unicode point

### ISSUE THREAD

**Issue by zeronone** [alanz/haskell-lsp#57]
I was trying out vscode-hie-server and encountered the following error.

```
[Error - 6:05:28 PM] haskell-lsp:Got setTraceNotification ignoring
[Error - 6:05:28 PM] haskell-lsp:no handler for. Object (fromList [("jsonrpc",String "2.0"),("params",Object (fromList [("settings",Object (fromList [("languageServerHaskell",Object (fromList [("maxNumberOfProblems",Number 100.0)]))]))])),("method",String "workspace/didChangeConfiguration")])
hie: /Users/khana/.stack/snapshots/x86_64-osx/lts-6.25/7.10.3/pkgdb/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!)
```

**Comment by wz1000** [comment]
HIE only currently only supports projects built with GHC-8.0.2. It seems like you are using 7.10.3

**Comment by razvan-panda** [comment]
`projects built with GHC-8.0.2`
`built with` <- the key part that confused me
cheers!

**Comment by razvan-panda** [comment]
@wz1000 does it work with GHC-8.2.1 also?

**Comment by jneira** [comment]
It seems we can close this one, hie nor haskell-lsp supported ghc-7.10.3 at the time (now hie does not support ghc-8.2.*) so i think we can close this.
