### ISSUE TITLE
New LSP features

### ISSUE THREAD

**Issue by alanz** [alanz/haskell-lsp#67]
See https://code.visualstudio.com/updates/v1_19#_language-server-protocol

"The language server protocol was extended with the following new feature: a completion context given access to the trigger character, more completion item and symbol kinds as well as markdown support for completion items and signature help. The protocol additions are available in the 4.0.0-next.x version of the client and server npm modules."

**Comment by Bubba** [comment]
- [ ] [Folding range](https://microsoft.github.io/language-server-protocol/specification#textDocument_foldingRange)
- [ ] (Color presentation)[
https://microsoft.github.io/language-server-protocol/specification#textDocument_colorPresentation]
- [ ] `preselect` in `CompletionItem`

**Comment by alanz** [comment]
This thing is moving *fast*.

**Comment by Bubba** [comment]
I think this has been superseded by #134

**Comment by jneira** [comment]
This *might* been superseded, closing
