### ISSUE TITLE
Compiler version support / DuplicateRecordFields

### ISSUE THREAD

**Issue by alanz** [alanz/haskell-lsp#7]
@adamwalker I am thinking of using `DuplicateRecordFields` to shorten the names. These are only available from GHC 8.0.

Will that be a problem for you?

**Comment by adamwalker** [comment]
Nope. Sounds like a good idea to me.

**Comment by alanz** [comment]
And I am going to prefix each and every record field with `_`.

I considered leaving it bare, but there are fields called `id`, `data`, `type`.

Using `lsp` as a prefix everywhere is an option, but as ugly as a leading `_` is it at least leaves the door open for anyone who is into lenses to use them idiomatically with this library.

**Comment by alanz** [comment]
And it seems that for GHC 8.0 we have to be explicit. So we end up with

```haskell
let doc = J.uriTextDocumentItem $ J.textDocumentDidOpenTextDocumentNotificationParams
                                $ fromJust $ J.paramsNotificationMessage notification
```

becoming

```haskell
 let
   params  = fromJust $ J._params (notification :: J.NotificationMessage J.DidSaveTextDocumentParams)
   textDoc = J._textDocument (params :: J.DidSaveTextDocumentParams)
   doc = J._uri (textDoc :: J.TextDocumentIdentifier)
```

See http://stackoverflow.com/questions/41008295/why-duplicaterecordfields-cannot-have-type-inference

This should improve in GHC 8.2

**Comment by alanz** [comment]
It is probably still worth doing, for the future benefits
