### ISSUE TITLE
Stack build error with resolver set to lts-9.21

### ISSUE THREAD

**Issue by HardRock** [alanz/haskell-lsp#73]
I'm trying to install the Haskell Ide Engine, but I get the following output when building haskell-lsp, using the resolver mentioned in the title:

`stack install haskell-lsp-0.2.0.1
haskell-lsp-0.2.0.1: configure
haskell-lsp-0.2.0.1: build

--  While building custom Setup.hs for package haskell-lsp-0.2.0.1 using:
      C:\Util\Stack\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe --builddir=.stack-work\dist\ca59d0ab build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure (-1073740940)
    Logs have been written to: C:\Util\Stack\global-project\.stack-work\logs\haskell-lsp-0.2.0.1.log

    Configuring haskell-lsp-0.2.0.1...
    Building haskell-lsp-0.2.0.1...
    Preprocessing library haskell-lsp-0.2.0.1...
    [ 1 of 10] Compiling Language.Haskell.LSP.TH.Constants ( src\Language\Haskell\LSP\TH\Constants.hs, .stack-work\dist\ca59d0ab\build\Language\Haskell\LSP\TH\Constants.o )
    [ 2 of 10] Compiling Language.Haskell.LSP.TH.ClientCapabilities ( src\Language\Haskell\LSP\TH\ClientCapabilities.hs, .stack-work\dist\ca59d0ab\build\Language\Haskell\LSP\TH\ClientCapabilities.o )`

Building it works fine when the resolvers for stack are either nightly-2017-11-24 or lts-11.2.

I'm fairly new to the stack build system, so I have no idea what could be the issue, the output isn't very helpful to me. Any assistance would be very much appreciated.

**Comment by jneira** [comment]
I've tried to build with `stack install haskell-lsp --resolver=lts-9.21` and i've hit the error described in #41 (it has a workaround)
However `haskell-ide-engine`no longer supports ghc-8.0.2 (the lower version now is ghc-8.4.2!) so i think it can be closed cause the goal was build hie. @HardRock, feel free to reopen if you think this still is sensible. 
Maybe we should drop support for older ghc's here too.
